//
//  ImageList.swift
//  ImageDemo
//
//  Created by cenk on 2025-01-24.
//

import SwiftUI

struct ImageList: View {
    var body: some View {
        ScrollView {
            VStack {
                ForEach(0..<4) { index in
                    Image("cat_city")
                        .resizable()
                        .aspectRatio(contentMode: .fit)
                        .overlay(alignment: .topLeading) {                    Image(systemName: "\(index + 1).circle.fill")
                                .resizable()
                                .frame(width: 60, height: 60)
                                .foregroundStyle(Color.blue)
                                .aspectRatio(contentMode: .fit)
                                .padding()
                        }
                }
                
//                ZStack {
//                    Rectangle()
//                        .foregroundStyle(.blue)
//                        .frame(width: 200, height: 150)
//                    Rectangle()
//                        .foregroundStyle(.orange)
//                        .frame(width: 100, height: 100)
//                }
                
            }
        }
    }
}


// Generated by Claude Sonnet 3.5
struct SonnetImageListView: View {
    
    static var tapCount = 0
    
    let tapAction: () -> Void = {
        SonnetImageListView.tapCount += 1
        print("Tapped \(SonnetImageListView.tapCount)")
    }
    
    var body: some View {
        ScrollView {
            VStack(spacing: 16) {
                
                CustomRectangle()
                    .stroke(lineWidth: 10)
                    .foregroundStyle(Color.green)
                
                ForEach(0..<5) { index in
                    ZStack(alignment: .topLeading) {
                        Image("cat_city")
                            .resizable()
                            .aspectRatio(contentMode: .fit)
                            .frame(maxWidth: .infinity)
                            .cornerRadius(12)
                            .shadow(radius: 4)
//                            .onTapGesture(count: 1, perform: {
//                                print("Tapped")
//                            })
//                            .onTapGesture {
//                                print("Tapped")
//                            }
                            .onTapGesture(perform: tapAction)
                            .gesture(TapGesture(count: 2)
                                .onEnded({ <#Void#> in
                                    <#code#>
                                }))
                        
                        
                        Capsule()
                            .fill(Color.red.opacity(0.7))
                            .frame(width: 60, height: 200)
                            .overlay(
                                Text("\(index + 1)")
                                    .foregroundColor(.white)
                                    .font(.system(size: 16, weight: .bold))
                            )
                            .padding(12)
                    }
                }
            }
            .padding()
        }
    }
}

struct CustomRectangle: Shape {
    func path(in rect: CGRect) -> Path {
        let path = CGMutablePath()
        path.move(to: rect.origin)
        path.addLine(to: CGPoint(x: rect.maxX, y: rect.minY))
        path.addLine(to: CGPoint(x: rect.minX, y: rect.minY))
        return Path(path)
    }
    
    
}

#Preview {
    // NOTE: Your preview can be a different SwiftUI View than the one you are working on.
    // Here we are not directly previewing on copy, but previewing how it looks doubled up in a VStack
    VStack {
        SonnetImageListView()
        SonnetImageListView()
    }
}
